### ISSUE TITLE
SecureCookieSession.__init__() got an unexpected keyword argument '_permanent'

### ISSUE THREAD

**Issue by butchewing** [kroketio/quart-session#17]
I'm using Quart **0.19.3** and quart-session **2.1.0**. After starting the following minimal sample

```python
from quart import Quart, session
from quart_session import Session

app = Quart(__name__)
app.config['SESSION_TYPE'] = 'redis'
app.config['SESSION_URI'] = 'redis://127.0.0.1:6379'
Session(app)


@app.route('/')
async def hello():
    session["foo"] = "bar"
    return "session key 'foo' set"


@app.route('/foo')
async def foo():
    return session.get("foo", "session key 'foo' not found")

app.run()

```
I'm getting the following error:
```
"quart_session/sessions.py", line 34, in __init__
    super(ServerSideSession, self).__init__(**initial or {})
TypeError: SecureCookieSession.__init__() got an unexpected keyword argument '_permanent'
```
This is related to [#15](https://github.com/kroketio/quart-session/issues/15).

**Comment by kroketio** [comment]
I cannot reproduce this issue. Why do you think it is related to #15?

**Comment by butchewing** [comment]
I thought it was related to #15 because it appeared at the same time after updating to Quart=**0.19.3** and quart-session=**2.0.0** prior to the release of quart-session=**2.0.1**.

**Error not raised**
Quart=**0.18.4** Quart-Session=**2.0.0**
Quart=**0.18.4** Quart-Session=**2.1.0**

**Error raised**
Quart=**0.19.0** skipped due to the QUART_ENV and env bug that was resolved in 0.19.1
Quart=**0.19.1** Quart-Session=**2.1.0**
Quart=**0.19.2** Quart-Session=**2.1.0**
Quart=**0.19.3** Quart-Session=**2.1.0**

**Comment by kroketio** [comment]
Works here:

```text
(venv) [s@s /tmp ]$ pip freeze | grep -iE 'quart|session'
Quart==0.19.3
quart-session==2.1.0

(venv) [s@s /tmp ]$ python3 main.py 
 * Serving Quart app 'main'
 * Debug mode: False
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Running on http://127.0.0.1:1800 (CTRL + C to quit)
```

**Comment by kroketio** [comment]
Thanks for investigating the affected versions. I was able to reproduce. 

Looks like Flask changed the interface(s) regarding session storage. Unfortunately I am currently quite busy, this means that for now quart-session works on `0.18` and not `0.19`. I will eventually get to fixing this (or someone else).

**Comment by PabloExperimental** [comment]
Hi, I solved with "_permanent" adding in the configuration SESSION_PERMANENT=True ( I think so...) .
But this is what happened next: 

 [2023-10-24 17:48:01 +0000] [13] [ERROR] Exception in ASGI application
 Traceback (most recent call last):

   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
     result = await app(  # type: ignore[func-returns-value]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
     return await self.app(scope, receive, send)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1621, in __call__
     await self.asgi_app(scope, receive, send)

   File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1647, in asgi_app
     await asgi_handler(receive, send)

   File "/usr/local/lib/python3.11/site-packages/quart/asgi.py", line 52, in __call__

   File "/usr/local/lib/python3.11/site-packages/quart/ctx.py", line 162, in __aenter__
     await self.push()

   File "/usr/local/lib/python3.11/site-packages/quart/ctx.py", line 142, in push
     await super()._push()

   File "/usr/local/lib/python3.11/site-packages/quart/ctx.py", line 103, in _push
     self.session = await self.app.ensure_async(session_interface.open_session)(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   File "/usr/local/lib/python3.11/site-packages/quart_session/sessions.py", line 148, in open_session
     res = self.session_class(data, sid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   
File "/usr/local/lib/python3.11/site-packages/quart_session/sessions.py", line 34, in __init__
     super(ServerSideSession, self).__init__(**initial or {})

 TypeError: SecureCookieSession.__init__() got an unexpected keyword argument '_addr'

**Comment by PabloExperimental** [comment]
From **quart_session/sessions.py**:

`
class ServerSideSession(SecureCookieSession):

    def __init__(self, initial=None, sid=None, permanent=None, addr=None):
        super(ServerSideSession, self).__init__(**initial or {})
        self.sid = sid
        if permanent:
            self.permanent = permanent
        if addr:
            self.addr = addr
        self.modified = False

    def dirty(self):
        current_app.logger.warning("Deprecation: `dirty()` has "
                                   "been made obsolete. Will be "
                                   "removed soon^tm.")

`
I think you have just change the constructor.

**Comment by urucoder** [comment]
The bug resides in that Quart uses the `SecureCookieSession` class from Flask, which expects the `initial` parameter, to solve it, the `ServerSideSession` class could call super passing the parameter as
```Python
def __init__(self, initial=None, sid=None, permanent=None, addr=None):
        super(ServerSideSession, self).__init__({"initial": initial})
        self.sid = sid
        if permanent:
            self.permanent = permanent
        if addr:
            self.addr = addr
        self.modified = False
```

for anyone needing a workaround with the current version, create a class extending the class `TaggedJSONSerializer` from `quart.json.tag` and override the `loads` method, create a custom session interface and use it as a serializer

```Python
class Serializer(TaggedJSONSerializer):
    def loads(self, value):
        return {"initial": super().loads(value)}

class CustomInterface(SessionInterface):
    def __init__(self, app, **options):
        self.serializer = Serializer()
        self.app = app
        super().__init__(**options)

class CustomSession(Session):
    def _get_interface(self, app):
        config = app.config.copy()
        # Set required defaults
        options = {#add your session options}
        return CustomInterface(app, **options)
```

**Comment by kroketio** [comment]
thanks for looking into it @urucoder. I am currently moving apartments and quite busy (also no internet), if you are able to create a PR ill test, confirm, and merge it. If not, ill get to it eventually.

**Comment by kroketio** [comment]
Latest version should work.

**Comment by urucoder** [comment]
@kroketio this bug is fixed in the last version, the issue should be closed
